Improve error messages for `Union` types in `Credentials`
guardicode/monkeytypes pull request #17
Opened 2023-12-19 12:18 UTC by shreyamalviya

Related to https://github.com/guardicore/monkey/issues/3942

Test script to see errors raised, with outputs: [error_messages_tests.zip](https://github.com/guardicode/monkeytypes/files/13715489/error_messages_tests.zip)

(This only works with dictionary inputs right now.)

2023-12-19 13:31 UTC, mssalvatore commented on monkeytypes/credentials/credentials.py
> +        custom_error_type=INVALID_UNION_MEMBER_ERROR,
Can we use pydantic's `union_tag_not_found` instead of having our own custom one?

2023-12-19 13:32 UTC, mssalvatore commented on monkeytypes/credentials/credentials.py
> +        custom_error_type=INVALID_UNION_MEMBER_ERROR,
NVM

2023-12-20 09:37 UTC, ilija-lazoroski approved these changes

2023-12-20 12:39 UTC, mssalvatore requested changes
I have the following issues when running unit tests:
```
__________________________________________________________ ERROR collecting tests/test_sshkeypair.py __________________________________________________________

ImportError while importing test module '/home/msalvatore/git/monkeytypes/tests/test_sshkeypair.py'.

Hint: make sure your test modules/packages have valid Python names.

Traceback:

/usr/lib/python3.11/importlib/__init__.py:126: in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

tests/test_sshkeypair.py:3: in <module>

    from monkeytypes import SSHKeypair

monkeytypes/__init__.py:44: in <module>

    from .credentials.credentials import Credentials, CredentialsComponent, Identity, Secret

monkeytypes/credentials/__init__.py:11: in <module>

    from .credentials import Credentials, CredentialsComponent, Identity, Secret

monkeytypes/credentials/credentials.py:5: in <module>

    from pydantic import Discriminator, Tag, field_serializer

E   ImportError: cannot import name 'Discriminator' from 'pydantic' (/home/msalvatore/git/monkeytypes/.venv/lib/python3.11/site-packages/pydantic/__init__.py)

=================================================================== short test summary info ===================================================================

ERROR tests/test_agent_plugin_manifest.py

ERROR tests/test_base_models.py

ERROR tests/test_credentials.py

ERROR tests/test_email_address.py

ERROR tests/test_file_extension.py

ERROR tests/test_int_range.py

ERROR tests/test_lm_hash.py

ERROR tests/test_network_range.py

ERROR tests/test_nt_hash.py

ERROR tests/test_password.py

ERROR tests/test_percent.py

ERROR tests/test_socket_address.py

ERROR tests/test_sshkeypair.py

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 13 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

===================================================================== 13 errors in 0.22s ======================================================================

```

If I'm reading the changelog correctly, it looks like you're using v2.5 features but we're using pydantic v2.4.

2023-12-20 12:59 UTC, mssalvatore requested changes
flake8 check fails. Are your pre-commit hooks working?

2023-12-20 13:36 UTC, mssalvatore approved these changes

2023-12-20 13:41 UTC, merged